import FeaturedBlogs from '@/components/Sections/featuredBlogs'
import HeroSection from '@/components/Sections/heroSection'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <section className='pb-40'>
        <Head>
          <title>codeSlayers - a blog for coders</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HeroSection />
        <FeaturedBlogs />
      </section>
    </>
  )
}
