import Head from 'next/head'
import Navbar from '@/components/Navbar/navbar'
import Footer from '@/components/Footer/footer'

export default function Home() {
  return (
    <div className='bg-backdrop'>
      <Head>
        <title>codeSlayers - a blog for coders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      <div className='px-8'>
        <h1 className='font-bold text-3xl text-center pt-10 pb-4'>&lt;/&gt; welcome 2 CodeSlayers &lt;/&gt;</h1>
        <p className="mx-60">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Vel soluta error aspernatur, magnam eveniet possimus saepe, alias commodi quas delectus distinctio ex repudiandae odio perspiciatis? Ab, optio! Unde id fugiat quo beatae dolorem libero explicabo provident temporibus. Rerum ad dicta commodi velit laborum sit autem libero? Eos, impedit a nobis eum distinctio sequi, odio beatae eveniet voluptate sed delectus, nam aliquam itaque corrupti. Possimus quam exercitationem eveniet ex illum minus id incidunt dicta, magnam dignissimos corporis maiores suscipit quia. Officia tenetur ex minus ipsum sed? Tempore, ipsam non quae consequuntur reprehenderit omnis earum velit suscipit a laborum pariatur quas id. Lorem ipsum dolor sit amet consectetur adipisicing elit. Facere, dicta sequi nostrum accusamus nam aut neque soluta doloremque officiis fuga atque quibusdam alias ea eligendi aliquid incidunt autem est quod esse nesciunt facilis ducimus ratione possimus natus! Ut ratione perspiciatis mollitia natus facere aut fugiat magni. Voluptate expedita fuga obcaecati debitis id excepturi ducimus inventore beatae! Cum placeat quia similique consectetur accusamus eveniet recusandae, debitis repudiandae nemo ab atque id. Pariatur ea accusamus nobis doloremque eveniet! Iusto rem cum blanditiis laboriosam facere? Alias magni incidunt cumque vel mollitia voluptates porro voluptate placeat aperiam dolor quaerat reiciendis exercitationem facilis iusto odit eligendi et, quam nihil distinctio, quos ratione laborum eos numquam reprehenderit! Dolor ad sint, aut et, voluptate vero culpa officia reiciendis, reprehenderit magnam sed beatae natus fugit! Explicabo provident cum voluptate perferendis culpa quas sunt repellendus! Omnis velit illum minima tenetur nesciunt, nisi numquam exercitationem, tempore illo quam fugit. Veniam ducimus sit iste nostrum asperiores, iure incidunt fugiat magni eius error. Corporis vitae laboriosam aut, voluptatem ipsa soluta assumenda quidem sequi amet quis facilis ut dolorum. Molestias beatae sunt ad aspernatur voluptatum laborum cupiditate accusantium in quod deserunt obcaecati doloribus vero ipsa, incidunt quibusdam eligendi possimus provident molestiae quia ipsam?</p>
      </div>
      <Footer />

    </div>
  )
}
